### ISSUE TITLE
Add health to the status 

### ISSUE THREAD

**Issue by pavolloffay** [os-observability/tempo-operator#165]
The status fields should contain health information

**Comment by andreasgerstmayr** [comment]
I'll add a Ready and Degraded condition as part of #153, PR coming soon. But it currently doesn't check the actual health, it only marks the tempo cluster as Degraded if the storage secret is missing or invalid.

**Comment by pavolloffay** [comment]
@rubenvp8510 is this done?

**Comment by rubenvp8510** [comment]
Yes
