### ISSUE TITLE
build fails - new cache does not exist

### ISSUE THREAD

**Issue by frzifus** [os-observability/tempo-operator#20]
Seems[/tmp/.buildx-cache-new](https://github.com/os-observability/tempo-operator/pull/18/files) does not exist.

CI (main): https://github.com/os-observability/tempo-operator/actions/runs/3050914986/jobs/4918544129#step:12:9

```
Run rm -rf /tmp/.buildx-cache
mv: cannot stat '/tmp/.buildx-cache-new': No such file or directory
Error: Process completed with exit code 1.
```

cc @iblancasa

**Comment by iblancasa** [comment]
@frzifus thanks for reporting this! Fixing...
