### ISSUE TITLE
add icon in ClusterServiceVersion

### ISSUE THREAD

**Issue by andreasgerstmayr** [os-observability/tempo-operator#200]

**Comment by pavolloffay** [comment]
Would it be the Tempo project icon? We might need to ask Grafana for permission to use it.

**Comment by joe-elliott** [comment]
Had a quick chat internally and you are welcome to use the Tempo image for the k8s operator. Thanks for taking on this work!

**Comment by pavolloffay** [comment]
That is awesome, thanks @joe-elliott
