### ISSUE TITLE
Add tempo gateway route support

### ISSUE THREAD

**Issue by frzifus** [os-observability/tempo-operator#223]

**Comment by pavolloffay** [comment]
This is partly done - the route is created when `openshift` mode is used. But it should be as well created when static/dynamic mode is used and deployed on OCP.

**Comment by pavolloffay** [comment]
This is realted to https://github.com/os-observability/tempo-operator/issues/222 (ingress support).

**Comment by pavolloffay** [comment]
dup of https://github.com/os-observability/tempo-operator/issues/318
