### ISSUE TITLE
rename TempoComponentsSpec entry in crd

### ISSUE THREAD

**Issue by frzifus** [os-observability/tempo-operator#229]
https://github.com/os-observability/tempo-operator/blob/542c7fb47a6d986f4d077c676ba681f5601ae583/apis/tempo/v1alpha1/microservices_types.go#L71

For me its a bit confusing that `Components` after json marshalling ends up as `template`. Whats your thoughts on that?

**Comment by andreasgerstmayr** [comment]
Yes that's weird, I'd recommend renaming it in json to `components`.
