### ISSUE TITLE
Create Defaulter and Validator for ProjectConfig

### ISSUE THREAD

**Issue by andreasgerstmayr** [os-observability/tempo-operator#266]
We should create a `Defaulter` and `Validator` for the `ProjectConfig` (the tempo-operator configuration), in a similar fashion how we set defaults and validate settings of the CR.

Setting the defaults and validating the configuration should happen during the startup of the operator.
If the validation fails, the operator should exit immediately.

Ref. discussion in https://github.com/os-observability/tempo-operator/pull/252#discussion_r1121924195

**Comment by pavolloffay** [comment]
>  (the tempo-operator configuration), in a similar fashion how we set defaults and validate settings of the CR.

Do I assume correctly that the impl will not sue the webhooks?

**Comment by andreasgerstmayr** [comment]
> > (the tempo-operator configuration), in a similar fashion how we set defaults and validate settings of the CR.
> 
> Do I assume correctly that the impl will not sue the webhooks?

Yes, this issue is about the operator configuration, which afaics never get validated through webhooks (the config needs to be valid before the webhook is started).

PR is in #281
