### ISSUE TITLE
Operator exposes traces about the Operand

### ISSUE THREAD

**Issue by frzifus** [os-observability/tempo-operator#291]
Not sure if it makes sense to have this configurable or simply send all traces to localhost.

See:
https://github.com/grafana/tempo/blob/d5e734c40216ad0db00c7c54cbe1ef685d90681a/docs/sources/tempo/operations/monitoring.md#traces
https://github.com/observatorium/api/blob/37022fddcd512d5b104c8ecfa22c4215d8cd7ff2/main.go#L241

**Comment by iblancasa** [comment]
I think it is a good point!
