### ISSUE TITLE
Create API/CRD docs

### ISSUE THREAD

**Issue by pavolloffay** [os-observability/tempo-operator#7]

**Comment by frzifus** [comment]
i can take this ⊂(◉‿◉)つ

**Comment by pavolloffay** [comment]
The #10 didn't resolve this ticket. 

The goal was to generate docs (similar to https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md) from the CRD (even empty one)

**Comment by frzifus** [comment]
@pavolloffay we did split this up: https://github.com/os-observability/tempo-operator/issues/11
