### ISSUE TITLE
Add ballast options across components

### ISSUE THREAD

**Issue by kevinearls** [os-observability/tempo-operator#74]
i.e. "-mem-ballast-size-mbs=1024"

See #63

**Comment by andreasgerstmayr** [comment]
Possibly we can skip this and implement `GOMEMLIMIT` instead:
https://github.com/golang/go/issues/23044#issuecomment-723262216
https://go.dev/doc/gc-guide#Memory_limit
https://weaviate.io/blog/2022/08/GOMEMLIMIT-a-Game-Changer-for-High-Memory-Applications.html
https://www.sobyte.net/post/2022-06/memory-ballast-gc-tuner/
https://github.com/grafana/tempo/pull/1758

**Comment by andreasgerstmayr** [comment]
In a test setup described at https://github.com/andreasgerstmayr/tempo-perf-eval/tree/main/ballast (in total 3000 virtual users sending traces every 1-5 seconds) I couldn't find significant improvements when setting ballast, therefore I'm closing this for now. Maybe we'll re-evaluate it at a later point.
